version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis-instance
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: "--requirepass mypassword --user username on > mypassword ~* allcommands --user default off nopass nocommands"
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint:
      /bin/sh -c "
        ollama serve &
        sleep 2 &&
        ollama pull gemma:2b &&
        ollama pull mxbai-embed-large &&
        wait
      "
    restart: unless-stopped

volumes:
  mongo-data:
  ollama-data:
