version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis-instance
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: "--requirepass mypassword --user username on > mypassword ~* allcommands --user default off nopass nocommands"
    volumes:
      - "redis-data:/data"
    restart: always

  mongo_rs0:
    image: mongo:latest
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017" ]
    ports:
      - "27017:27017"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo-data:/data/db"
      - "mongo-config:/data/configdb"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    volumes:
      - "minio-data:/data"
    command: server /data --console-address ":9001"

  create-minio-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio miniominio;
      /usr/bin/mc mb myminio/main-storage;
      exit 0;
      "

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint:
      /bin/sh -c "
      ollama serve &
      sleep 2 &&
      ollama pull gemma:2b &&
      ollama pull mxbai-embed-large &&
      wait
      "
    restart: unless-stopped

volumes:
  mongo-data:
  mongo-config:
  ollama-data:
  redis-data:
  minio-data:
